### ISSUE TITLE
Could not upload to S3 when device time is skewed by more than 5 minute

### ISSUE THREAD

**Issue by arundevma** [AFNetworking/AFAmazonS3Manager#68]
When I try to upload to s3 when my device time is wrong, I am getting error. Upload gets stuck in the middle and I get a time out error.

**Comment by mattt** [comment]
This is expected behavior. AWS uses a time signature to invalidate credentials after a certain time. Since this is calculated from the current device time, one could only expect this not to work correctly if that device time is incorrect.

I'm not particularly concerned about this situation, since S3 functionality requires an internet connection, from which the correct time can be synchronized.
